### This is a GitHub Actions workflow file for a Terraform pipeline.
### It triggers on pushes to the 'dev' branch and only if files in the 'terraform' directory are changed.
### The pipeline performs the following steps:
### 1. Checks out the code from the repository.
### 2. Sets up Terraform using a specific version.
### 3. Changes the working directory to 'terraform'.
name: Terraform Pipeline

on:
  push:
    branches:
      - dev
    paths:
      - terraform/**

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Change to terraform directory
        run: cd terraform
      
      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.terraform}}'
          

      - name: Initialize Terraform
        run: terraform -chdir=terraform init

      - name: Validate Terraform configuration
        run: terraform -chdir=terraform validate

      - name: Plan Terraform changes
        run: terraform -chdir=terraform plan

      - name: Apply Terraform changes
        run: terraform -chdir=terraform apply -auto-approve
